### ISSUE TITLE
Player Class: subtractMoney

### ISSUE THREAD

**Issue by NathanHealea** [cs361-W16/Blackjack-21#16]
**Overview:** 
Deduct Money decreases the money amount the player has.
**Pre-Condition:** 
Should take an int that will be deducted from the players money amount.
**Post Condition:**
Players money will be deducted the amount.
**Return:**
None

**Comment by NathanHealea** [comment]
My not be needed.

**Comment by Sedwick** [comment]
I have this covered.

**Comment by Sedwick** [comment]
The function I have is actually winBet() or loseBet(). If the Player wins, run winBet() and it automatically applys the bet to their pot (money on hand). Same thing for loseBet(), it subtracts the bet from their pot.
